server:
  port: 8001
spring:
  application:
    name: short-link-project
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 139.159.224.143:8848
        namespace: 03e1511c-a459-49bc-a3b4-bc7d420e291b

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.squirrel.project.dao.entity
  configuration:
    map-underscore-to-camel-case: true

short-link:
  stats:
    locale:
      amap-key: 38e9e76ff59f23c098758b98c5063b33
  goto-domain:
    white-list:
      enable: true
      names: "拿个offer，知乎，掘金，博客园"
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
  domain:
    default: nurl.ink:8001