server:
  port: 8002

spring:
  application:
    name: short-link-admin
  datasource:
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456